version: '3.8'

services:
  web:
    build: . #The . tells docker compose to build the web service from the docker file in the current directory
    ports:
      - "5002:5002"
    depends_on:
      - mydb

  mydb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw