version: '3.8'  #The version tells docker compose which version of the file format we're using

services:  #The services is where we list all the different parts of our app, which is the web service(our flask application) and a database
  web:
    image:  043309335662.dkr.ecr.us-east-1.amazonaws.com/ecr-flask-mysql:latest  #Instead of building the image locally we are going to replace it with image and paste our ecr repository
    ports:
      - "5002:5002"
    depends_on:  #We set the ports to 5002 for the web service
      - mydb



  mydb:
    image: mysql:8 #We are using an image we found online, this tells docker compose which image version we're using
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw   #We set the environment variable mysql root password which we set to my secret pw