
version: "3.8"

services: 
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis



  redis: 
    image: redis:latest
    ports:
      - "6379:6379"

  
  # redis_data_persist:
  #   container_name: redis_data_persist
  #   command: bash -c "redis-server --appendonly yes --requirepass <password>"
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redis-volume:/data